export const products = [
  {
    id: 1,
    name: "Monstera Deliciosa",
    category: "Indoor plants",
    price: 45.00,
    stock: 12,
    rating: 4.8,
    reviewCount: 156,
    image: "https://picsum.photos/seed/monstera/600/800",
    description: "The iconic Swiss Cheese plant. A vining epiphytic plant that will eventually require a support to climb.",
    care: { light: "Bright indirect", water: "Allow top 2 inches to dry", difficulty: "Easy" },
    sellerName: "Fernshop Nursery"
  },
  {
    id: 2,
    name: "Ficus Lyrata",
    category: "Indoor plants",
    price: 65.00,
    stock: 5,
    rating: 4.5,
    reviewCount: 89,
    image: "https://picsum.photos/seed/ficus/600/800",
    description: "Commonly known as the Fiddle Leaf Fig. Features large, heavily veined, and violin-shaped leaves that grow upright.",
    care: { light: "Bright indirect", water: "Water when topsoil is dry", difficulty: "Moderate" },
    sellerName: "Fernshop Nursery"
  },
  {
    id: 3,
    name: "Terracotta Cylinder",
    category: "Pots & planters",
    price: 24.99,
    stock: 0,
    rating: 4.9,
    reviewCount: 210,
    image: "https://picsum.photos/seed/terracotta/600/800",
    description: "A classic cylindrical unglazed terracotta pot. Perfect for plants that prefer dry soil, as the porous material breathes.",
    care: { light: "N/A", water: "N/A", difficulty: "N/A" },
    sellerName: "Artisan Pots Co."
  },
  {
    id: 4,
    name: "Zamioculcas Zamiifolia",
    category: "Indoor plants",
    price: 32.50,
    stock: 18,
    rating: 4.7,
    reviewCount: 342,
    image: "https://picsum.photos/seed/zz/600/800",
    description: "The ZZ Plant is an incredibly tough indoor plant. Its shiny, oval leaves on thick stalks make it visually striking.",
    care: { light: "Low to bright indirect", water: "Water sparingly", difficulty: "Very Easy" },
    sellerName: "Fernshop Nursery"
  },
  {
    id: 5,
    name: "Calathea Orbifolia",
    category: "Indoor plants",
    price: 42.00,
    stock: 3,
    rating: 4.4,
    reviewCount: 64,
    image: "https://picsum.photos/seed/calathea/600/800",
    description: "Known for its large, round, silver-green leaves with pronounced dark green striping. A beautiful statement plant.",
    care: { light: "Medium indirect", water: "Keep consistently moist", difficulty: "Hard" },
    sellerName: "Fernshop Nursery"
  },
  {
    id: 6,
    name: "Neem Oil Spray",
    category: "Plant care",
    price: 14.50,
    stock: 45,
    rating: 4.6,
    reviewCount: 128,
    image: "https://picsum.photos/seed/neem/600/800",
    description: "Organic, cold-pressed neem oil blend ready to use. Keeps pests at bay while polishing plant leaves.",
    care: { light: "Store in dark", water: "N/A", difficulty: "N/A" },
    sellerName: "Botanical Care Inc."
  },
  {
    id: 7,
    name: "Philodendron Gloriosum",
    category: "Indoor plants",
    price: 85.00,
    stock: 2,
    rating: 4.9,
    reviewCount: 45,
    image: "https://picsum.photos/seed/gloriosum/600/800",
    description: "A crawling Philodendron featuring massive, velvety, heart-shaped leaves with prominent white veins.",
    care: { light: "Bright indirect", water: "Water when half dry", difficulty: "Moderate" },
    sellerName: "Rare Plants Collective"
  },
  {
    id: 8,
    name: "Ceramic Catchall Tray",
    category: "Pots & planters",
    price: 18.00,
    stock: 14,
    rating: 4.8,
    reviewCount: 76,
    image: "https://picsum.photos/seed/tray/600/800",
    description: "A glazed ceramic saucer to protect your floors and furniture from water damage. Available in matte white.",
    care: { light: "N/A", water: "N/A", difficulty: "N/A" },
    sellerName: "Artisan Pots Co."
  },
  {
    id: 9,
    name: "Epipremnum Aureum",
    category: "Indoor plants",
    price: 16.00,
    stock: 25,
    rating: 4.7,
    reviewCount: 890,
    image: "https://picsum.photos/seed/pothos/600/800",
    description: "Golden Pothos is arguably the easiest houseplant to grow. Features long trailing vines with heart-shaped leaves.",
    care: { light: "Low to bright", water: "Allow to dry out", difficulty: "Very Easy" },
    sellerName: "Fernshop Nursery"
  },
  {
    id: 10,
    name: "Premium Aroid Mix",
    category: "Plant care",
    price: 22.00,
    stock: 0,
    rating: 4.9,
    reviewCount: 112,
    image: "https://picsum.photos/seed/soil/600/800",
    description: "A chunky, well-draining soil mix formulated specifically for aroids. Contains orchid bark, perlite, and charcoal.",
    care: { light: "Store sealed", water: "N/A", difficulty: "N/A" },
    sellerName: "Botanical Care Inc."
  },
  {
    id: 11,
    name: "Brass Plant Mister",
    category: "Plant care",
    price: 34.00,
    stock: 8,
    rating: 4.3,
    reviewCount: 52,
    image: "https://picsum.photos/seed/mister/600/800",
    description: "An elegant brass mister that produces a fine, gentle spray for humidity-loving plants. Beautiful enough to leave on display.",
    care: { light: "N/A", water: "Rinse weekly", difficulty: "N/A" },
    sellerName: "Metalworks Studio"
  },
  {
    id: 12,
    name: "Strelitzia Nicolai",
    category: "Indoor plants",
    price: 95.00,
    stock: 4,
    rating: 4.6,
    reviewCount: 134,
    image: "https://picsum.photos/seed/strelitzia/600/800",
    description: "The White Bird of Paradise. Brings an instant tropical feel indoors with its massive, banana-like leaves.",
    care: { light: "Direct sun", water: "Keep evenly moist", difficulty: "Moderate" },
    sellerName: "Fernshop Nursery"
  }
];
